import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import path from 'node:path'

// HTTPS only when the certificate actually exists.
//
// Generated by scripts/gen-dev-cert.sh. Absent -- the normal case -- the dev
// server stays on plain http and nothing changes. Present, it serves https so
// the page and the API are on the same scheme; an https page calling an http
// API is blocked by the browser as mixed content, so half-enabling TLS is
// worse than leaving it off.
const certDir = path.resolve(import.meta.dirname ?? '.', 'certs')
const keyPath = path.join(certDir, 'key.pem')
const certPath = path.join(certDir, 'cert.pem')
const https =
  fs.existsSync(keyPath) && fs.existsSync(certPath)
    ? { key: fs.readFileSync(keyPath), cert: fs.readFileSync(certPath) }
    : undefined

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    // WITHOUT THIS THE PHONE CANNOT REACH THE DEV SERVER AT ALL.
    //
    // Vite binds to 127.0.0.1 by default, which only accepts connections from
    // the same machine. `host: true` binds every interface, so
    // http://<your-laptop-LAN-IP>:5173 works from a handset on the same wifi.
    // Vite prints the exact address as "Network:" when it starts.
    host: true,
    port: 5173,
    https,
    // Fail loudly instead of silently moving to 5174, which would leave the
    // backend's CORS allowlist pointing at a port nothing is serving.
    strictPort: true,
  },
})
